export const MINDFULNESS_QUESTIONS: string[] = [
  // ✅ Tus preguntas (del TXT)
  "¿Qué actividad te hace perder la noción del tiempo? ¿Por qué?",
  "¿Cuál es un pequeño acto de amabilidad que puedes hacer por alguien hoy?",
  "Piensa en un desafío que superaste. ¿Qué aprendiste de él?",
  "¿Qué es algo hermoso que notaste recientemente?",
  "Describe un lugar donde te sientas completamente en paz.",
  "¿Qué cualidad admiras en los demás que también ves en ti mismo/a?",
  "¿Cuáles son tres cosas por las que estás agradecido/a hoy?",
  "Describe un sonido que escuches ahora mismo. ¿Qué te hace pensar?",

  // ✅ Nuevas (30 aprox.)
  "¿Qué sensación física notas ahora mismo (tensión, ligereza, calor)?",
  "¿Qué emoción está más presente hoy? ¿Dónde la sientes en el cuerpo?",
  "Si pudieras darte un consejo amable ahora mismo, ¿cuál sería?",
  "¿Qué es lo más importante de hoy (solo una cosa)?",
  "¿Qué necesitas hoy: descanso, apoyo, claridad o acción?",
  "¿Qué pensamiento se repite últimamente? ¿Te ayuda o te pesa?",
  "¿Qué puedes soltar en este momento aunque sea un 5%?",
  "¿Qué parte del día te gustaría vivir más despacio?",
  "¿Qué pequeño paso te acercaría a sentirte mejor en 10 minutos?",
  "¿Qué estás evitando mirar? ¿Qué pasaría si lo miras con calma 30 segundos?",
  "¿Qué te está diciendo tu cuerpo con esta tensión o cansancio?",
  "¿Qué te ha hecho sonreír (aunque sea mínimo) en las últimas 24h?",
  "¿Qué agradeces de tu cuerpo hoy?",
  "¿Qué estás haciendo bien últimamente, aunque no lo valores?",
  "¿Qué te gustaría escuchar de alguien ahora mismo? Dítelo tú.",
  "¿Qué límite sano necesitas poner esta semana?",
  "¿Qué puedes simplificar hoy?",
  "¿Qué te da energía y qué te la quita?",
  "¿Qué es una cosa que puedes aceptar hoy tal como es?",
  "¿Qué te preocupa? ¿Qué parte está bajo tu control?",
  "Si tu mente fuera el cielo, ¿qué “clima” hay ahora? (nubes, sol, tormenta...)",
  "¿Qué cosa pequeña puedes celebrar hoy?",
  "¿Qué te estás exigiendo de más?",
  "¿Qué te gustaría dejar para mañana sin culpa?",
  "¿Qué valor quieres practicar hoy? (paciencia, honestidad, calma...)",
  "¿Qué necesitas perdonarte hoy?",
  "¿Qué te gustaría que fuera más ligero en tu vida?",
  "¿Qué pensamiento puedes cambiar por uno más realista y amable?",
  "¿Qué te gustaría priorizar esta tarde?",
  "¿Qué te hace sentir en casa contigo?",
];
